# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pluses' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for pluses
  pod 'Google/SignIn'

  target 'plusesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'pluses-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for pluses-tvOS

  target 'pluses-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
